### PR TITLE
Wording

### PR DESCRIPTION
**Pull request by wrueting**

### CODE REVIEW

**Comment by wrueting** [comment]
Have a look at the table Interfaces (Schnittstellentechnologien) WCF was changed to SOAP

**Comment by fiscoal** [comment]
**First PR of @wrueting** 🥳 👍🏻

But SOAP really is not available on Unix?

**Review by ghost — COMMENTED** [review]
**First PR of @wrueting** 🥳 👍🏻

But SOAP really is not available on Unix?

**Comment by ghost** [comment]
@TSchmiedlechner, could you quickly confirm if SOAP was not available on Unix? Talked to PosCreator briefly and it should be available.

If that was the case, the next question is what would WCF refer to in this context.

**Pull request merged**
